-- Identidad multi-tenant para INJOE Mecánicos
-- Idempotente: se puede volver a ejecutar sin romper datos existentes.

CREATE TABLE IF NOT EXISTS empresas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    ruc VARCHAR(13) NOT NULL,
    direccion TEXT NOT NULL,
    telefono VARCHAR(20),
    correo VARCHAR(255),
    sri_id INTEGER,
    moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    idioma VARCHAR(5) NOT NULL DEFAULT 'es',
    zona_horaria VARCHAR(50) NOT NULL DEFAULT 'America/Guayaquil',
    entorno_sri VARCHAR(1) NOT NULL DEFAULT '1',
    ruta_logo VARCHAR(255),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    verificada BOOLEAN NOT NULL DEFAULT FALSE,
    plan_suscripcion VARCHAR(50) NOT NULL DEFAULT 'basic',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_empresas_slug UNIQUE (slug),
    CONSTRAINT uq_empresas_ruc UNIQUE (ruc),
    CONSTRAINT ck_empresas_entorno_sri CHECK (entorno_sri IN ('1', '2'))
);

CREATE TABLE IF NOT EXISTS puntos_emision (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision VARCHAR(20) NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    factura_seq BIGINT NOT NULL DEFAULT 0,
    nota_credito_seq BIGINT NOT NULL DEFAULT 0,
    nota_debito_seq BIGINT NOT NULL DEFAULT 0,
    retencion_seq BIGINT NOT NULL DEFAULT 0,
    liquidacion_compra_seq BIGINT NOT NULL DEFAULT 0,
    guia_remision_seq BIGINT NOT NULL DEFAULT 0,
    info TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_puntos_emision_empresa_id ON puntos_emision (empresa_id);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    correo VARCHAR NOT NULL,
    nombre_usuario VARCHAR NOT NULL,
    nombre_completo VARCHAR NOT NULL,
    contrasena_hash VARCHAR NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    verificado BOOLEAN NOT NULL DEFAULT FALSE,
    ultimo_acceso TIMESTAMPTZ,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_usuarios_correo_empresa UNIQUE (correo, empresa_id),
    CONSTRAINT uq_usuarios_nombre_usuario_empresa UNIQUE (nombre_usuario, empresa_id)
);

CREATE INDEX IF NOT EXISTS ix_usuarios_correo ON usuarios (correo);
CREATE INDEX IF NOT EXISTS ix_usuarios_nombre_usuario ON usuarios (nombre_usuario);
CREATE INDEX IF NOT EXISTS ix_usuarios_empresa_id ON usuarios (empresa_id);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR NOT NULL,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR,
    es_sistema BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_roles_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS permisos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR NOT NULL,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR,
    es_sistema BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_permisos_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS roles_permisos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permiso_id INTEGER NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
    CONSTRAINT uq_roles_permisos UNIQUE (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS usuarios_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT uq_usuarios_roles UNIQUE (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS usuarios_puntos_emision (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id) ON DELETE CASCADE,
    CONSTRAINT uq_usuarios_puntos_emision UNIQUE (usuario_id, punto_emision_id)
);

CREATE INDEX IF NOT EXISTS ix_usuarios_puntos_emision_usuario ON usuarios_puntos_emision (usuario_id);
CREATE INDEX IF NOT EXISTS ix_usuarios_puntos_emision_punto ON usuarios_puntos_emision (punto_emision_id);
