-- Catálogo de servicios por empresa y punto de emisión
-- Idempotente.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'categoria_servicio') THEN
        CREATE TYPE categoria_servicio AS ENUM (
            'consultoria', 'desarrollo', 'mantenimiento', 'soporte', 'capacitacion', 'otros'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_impuesto') THEN
        CREATE TYPE tipo_impuesto AS ENUM (
            '0', '5', '15', 'no_objeto', 'exento_iva'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS servicios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    categoria categoria_servicio,
    precio_venta NUMERIC(10, 2) NOT NULL,
    aplica_iva BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_impuesto tipo_impuesto NOT NULL,
    peso NUMERIC(10, 2),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_servicios_codigo_punto UNIQUE (empresa_id, punto_emision_id, codigo),
    CONSTRAINT ck_servicios_precio_venta CHECK (precio_venta > 0),
    CONSTRAINT ck_servicios_peso CHECK (peso IS NULL OR peso >= 0)
);

CREATE INDEX IF NOT EXISTS ix_servicios_empresa_id ON servicios (empresa_id);
CREATE INDEX IF NOT EXISTS ix_servicios_punto_emision_id ON servicios (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_servicios_codigo ON servicios (codigo);
CREATE INDEX IF NOT EXISTS ix_servicios_nombre ON servicios (nombre);
