-- Inventario: categorías, bodegas, productos, existencias y movimientos.
-- Idempotente. Reutiliza tipo_impuesto de 0003_servicios.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_movimiento_inventario') THEN
        CREATE TYPE tipo_movimiento_inventario AS ENUM (
            'INGRESO', 'SALIDA', 'AJUSTE', 'TRANSFERENCIA', 'STOCK_INICIAL'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_ajuste_inventario') THEN
        CREATE TYPE tipo_ajuste_inventario AS ENUM (
            'INGRESO', 'EGRESO'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS categorias_producto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_categorias_producto_nombre_punto UNIQUE (empresa_id, punto_emision_id, nombre)
);

CREATE INDEX IF NOT EXISTS ix_categorias_producto_empresa_id ON categorias_producto (empresa_id);
CREATE INDEX IF NOT EXISTS ix_categorias_producto_punto_emision_id ON categorias_producto (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_categorias_producto_nombre ON categorias_producto (nombre);

CREATE TABLE IF NOT EXISTS bodegas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    nombre VARCHAR(120) NOT NULL,
    ubicacion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_bodegas_nombre_punto UNIQUE (empresa_id, punto_emision_id, nombre)
);

CREATE INDEX IF NOT EXISTS ix_bodegas_empresa_id ON bodegas (empresa_id);
CREATE INDEX IF NOT EXISTS ix_bodegas_punto_emision_id ON bodegas (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_bodegas_nombre ON bodegas (nombre);

CREATE TABLE IF NOT EXISTS productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    codigo VARCHAR(20) NOT NULL,
    codigo_barras VARCHAR(64),
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    categoria_id INTEGER NOT NULL REFERENCES categorias_producto(id),
    precio_venta NUMERIC(10, 2) NOT NULL,
    aplica_iva BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_impuesto tipo_impuesto NOT NULL,
    stock_minimo NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock_maximo NUMERIC(12, 2),
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'UN',
    peso NUMERIC(10, 2),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_productos_codigo_punto UNIQUE (empresa_id, punto_emision_id, codigo),
    CONSTRAINT ck_productos_precio_venta CHECK (precio_venta > 0),
    CONSTRAINT ck_productos_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_productos_stock_maximo CHECK (stock_maximo IS NULL OR stock_maximo >= 0),
    CONSTRAINT ck_productos_peso CHECK (peso IS NULL OR peso >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_productos_codigo_barras_punto
    ON productos (empresa_id, punto_emision_id, codigo_barras)
    WHERE codigo_barras IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_productos_empresa_id ON productos (empresa_id);
CREATE INDEX IF NOT EXISTS ix_productos_punto_emision_id ON productos (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_productos_codigo ON productos (codigo);
CREATE INDEX IF NOT EXISTS ix_productos_nombre ON productos (nombre);
CREATE INDEX IF NOT EXISTS ix_productos_categoria_id ON productos (categoria_id);

CREATE TABLE IF NOT EXISTS existencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    bodega_id INTEGER NOT NULL REFERENCES bodegas(id),
    cantidad NUMERIC(12, 2) NOT NULL DEFAULT 0,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_existencias_producto_bodega UNIQUE (producto_id, bodega_id),
    CONSTRAINT ck_existencias_cantidad CHECK (cantidad >= 0)
);

CREATE INDEX IF NOT EXISTS ix_existencias_producto_id ON existencias (producto_id);
CREATE INDEX IF NOT EXISTS ix_existencias_bodega_id ON existencias (bodega_id);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    codigo VARCHAR(20) NOT NULL,
    tipo tipo_movimiento_inventario NOT NULL,
    bodega_id INTEGER NOT NULL REFERENCES bodegas(id),
    bodega_destino_id INTEGER REFERENCES bodegas(id),
    tipo_ajuste tipo_ajuste_inventario,
    nota VARCHAR(255),
    observacion VARCHAR(500),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_movimientos_inventario_codigo_punto UNIQUE (empresa_id, punto_emision_id, codigo),
    CONSTRAINT ck_movimientos_transferencia CHECK (
        (tipo <> 'TRANSFERENCIA' AND bodega_destino_id IS NULL)
        OR (tipo = 'TRANSFERENCIA' AND bodega_destino_id IS NOT NULL AND bodega_destino_id <> bodega_id)
    ),
    CONSTRAINT ck_movimientos_ajuste CHECK (
        (tipo <> 'AJUSTE' AND tipo_ajuste IS NULL)
        OR (tipo = 'AJUSTE' AND tipo_ajuste IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_empresa_id ON movimientos_inventario (empresa_id);
CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_punto_emision_id ON movimientos_inventario (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_tipo ON movimientos_inventario (tipo);
CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_bodega_id ON movimientos_inventario (bodega_id);
CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_creado_en ON movimientos_inventario (creado_en);

CREATE TABLE IF NOT EXISTS movimientos_inventario_lineas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id INTEGER NOT NULL REFERENCES movimientos_inventario(id) ON DELETE CASCADE,
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad NUMERIC(12, 2) NOT NULL,
    stock_origen_despues NUMERIC(12, 2) NOT NULL,
    stock_destino_despues NUMERIC(12, 2),
    CONSTRAINT ck_movimientos_lineas_cantidad CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_lineas_movimiento_id ON movimientos_inventario_lineas (movimiento_id);
CREATE INDEX IF NOT EXISTS ix_movimientos_inventario_lineas_producto_id ON movimientos_inventario_lineas (producto_id);
