-- Proveedores, precios de compra y flag de inventario en productos.
-- Idempotente.

ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS aplica_inventario BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    identificacion VARCHAR(13) NOT NULL,
    tipo_persona tipo_cliente NOT NULL DEFAULT 'PERSONA_NATURAL',
    nombres VARCHAR(255) NOT NULL,
    razon_social VARCHAR(255),
    direccion TEXT,
    telefono VARCHAR(20),
    correo VARCHAR(255),
    direccion_fiscal TEXT,
    telefono_fiscal VARCHAR(20),
    correo_fiscal VARCHAR(255),
    notas TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_proveedores_identificacion_punto UNIQUE (empresa_id, punto_emision_id, identificacion)
);

CREATE INDEX IF NOT EXISTS ix_proveedores_empresa_id ON proveedores (empresa_id);
CREATE INDEX IF NOT EXISTS ix_proveedores_punto_emision_id ON proveedores (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_proveedores_nombres ON proveedores (nombres);
CREATE INDEX IF NOT EXISTS ix_proveedores_identificacion ON proveedores (identificacion);

CREATE TABLE IF NOT EXISTS productos_proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id) ON DELETE CASCADE,
    precio_compra NUMERIC(10, 2) NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_productos_proveedores UNIQUE (producto_id, proveedor_id),
    CONSTRAINT ck_productos_proveedores_precio CHECK (precio_compra >= 0)
);

CREATE INDEX IF NOT EXISTS ix_productos_proveedores_producto_id ON productos_proveedores (producto_id);
CREATE INDEX IF NOT EXISTS ix_productos_proveedores_proveedor_id ON productos_proveedores (proveedor_id);

CREATE TABLE IF NOT EXISTS servicios_proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_id INTEGER NOT NULL REFERENCES servicios(id) ON DELETE CASCADE,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id) ON DELETE CASCADE,
    precio_compra NUMERIC(10, 2) NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_servicios_proveedores UNIQUE (servicio_id, proveedor_id),
    CONSTRAINT ck_servicios_proveedores_precio CHECK (precio_compra >= 0)
);

CREATE INDEX IF NOT EXISTS ix_servicios_proveedores_servicio_id ON servicios_proveedores (servicio_id);
CREATE INDEX IF NOT EXISTS ix_servicios_proveedores_proveedor_id ON servicios_proveedores (proveedor_id);
