-- Órdenes de trabajo y alta rápida: identificación de cliente opcional.
-- Idempotente.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_orden_trabajo') THEN
        CREATE TYPE estado_orden_trabajo AS ENUM ('EN_PROCESO', 'CERRADA');
    END IF;
END
$$;

ALTER TABLE clientes ALTER COLUMN identificacion DROP NOT NULL;

ALTER TABLE clientes DROP CONSTRAINT IF EXISTS uq_clientes_identificacion_punto;

CREATE UNIQUE INDEX IF NOT EXISTS uq_clientes_identificacion_punto
    ON clientes (empresa_id, punto_emision_id, identificacion)
    WHERE identificacion IS NOT NULL;

CREATE TABLE IF NOT EXISTS ordenes_trabajo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    numero VARCHAR(20) NOT NULL,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
    vehiculo_id INTEGER NOT NULL REFERENCES vehiculos(id),
    tecnico_id INTEGER NOT NULL REFERENCES usuarios(id),
    estado estado_orden_trabajo NOT NULL DEFAULT 'EN_PROCESO',
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_entrega TIMESTAMPTZ,
    kilometraje NUMERIC(10, 2),
    notas_generales TEXT,
    notas_tecnicas TEXT,
    total_productos NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_servicios NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_costo NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_utilidad NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_ordenes_trabajo_numero_punto UNIQUE (empresa_id, punto_emision_id, numero)
);

CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_empresa_id ON ordenes_trabajo (empresa_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_punto_emision_id ON ordenes_trabajo (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_cliente_id ON ordenes_trabajo (cliente_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_vehiculo_id ON ordenes_trabajo (vehiculo_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_tecnico_id ON ordenes_trabajo (tecnico_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_estado ON ordenes_trabajo (estado);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_fecha_inicio ON ordenes_trabajo (fecha_inicio);

CREATE TABLE IF NOT EXISTS ordenes_trabajo_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id INTEGER NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
    producto_id INTEGER REFERENCES productos(id),
    servicio_id INTEGER REFERENCES servicios(id),
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id),
    bodega_id INTEGER REFERENCES bodegas(id),
    descripcion VARCHAR(500) NOT NULL,
    codigo VARCHAR(50),
    cantidad NUMERIC(10, 2) NOT NULL,
    precio_venta NUMERIC(10, 2) NOT NULL,
    precio_compra NUMERIC(10, 2) NOT NULL DEFAULT 0,
    aplica_iva BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_impuesto tipo_impuesto NOT NULL,
    utilidad NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT ck_ordenes_items_tipo CHECK (
        (producto_id IS NOT NULL AND servicio_id IS NULL)
        OR (producto_id IS NULL AND servicio_id IS NOT NULL)
    ),
    CONSTRAINT ck_ordenes_items_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_ordenes_items_precio_venta CHECK (precio_venta >= 0),
    CONSTRAINT ck_ordenes_items_precio_compra CHECK (precio_compra >= 0)
);

CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_items_orden_id ON ordenes_trabajo_items (orden_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_items_producto_id ON ordenes_trabajo_items (producto_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_items_servicio_id ON ordenes_trabajo_items (servicio_id);
CREATE INDEX IF NOT EXISTS ix_ordenes_trabajo_items_proveedor_id ON ordenes_trabajo_items (proveedor_id);
