-- Catálogo SRI de formas de pago, formas por empresa/punto y sri_id local de injoedev.
-- Idempotente.

CREATE TABLE IF NOT EXISTS formas_pago_sri (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_formas_pago_sri_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS formas_pago (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    codigo VARCHAR(30) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    forma_pago_sri_id INTEGER REFERENCES formas_pago_sri(id),
    aplica_venta BOOLEAN NOT NULL DEFAULT TRUE,
    aplica_compra BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_formas_pago_empresa_codigo UNIQUE (empresa_id, punto_emision_id, codigo)
);

CREATE INDEX IF NOT EXISTS ix_formas_pago_empresa_id ON formas_pago (empresa_id);
CREATE INDEX IF NOT EXISTS ix_formas_pago_punto_emision_id ON formas_pago (punto_emision_id);

INSERT INTO formas_pago_sri (codigo, nombre, activo)
VALUES
    ('01', 'Sin utilización del sistema financiero', TRUE),
    ('15', 'Compensación de Deudas', TRUE),
    ('16', 'Tarjeta de Débito', TRUE),
    ('17', 'Dinero Electrónico', FALSE),
    ('18', 'Tarjeta de Prepago', FALSE),
    ('19', 'Tarjeta de Crédito', TRUE),
    ('20', 'Otros con utilización del sistema financiero', TRUE),
    ('21', 'Endoso de Títulos', FALSE)
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO formas_pago (
    empresa_id, punto_emision_id, codigo, nombre, forma_pago_sri_id, aplica_venta, aplica_compra, activo
)
SELECT
    pe.empresa_id,
    pe.id,
    plantilla.codigo,
    plantilla.nombre,
    sri.id,
    plantilla.aplica_venta,
    plantilla.aplica_compra,
    TRUE
FROM puntos_emision pe
CROSS JOIN (
    VALUES
        ('EFE001', 'Efectivo', '01', TRUE, TRUE),
        ('CHE001', 'Cheque', '20', TRUE, TRUE),
        ('TRA001', 'Transferencia', '20', TRUE, TRUE),
        ('TDE001', 'Tarjeta de Débito', '16', TRUE, FALSE),
        ('TCR001', 'Tarjeta de crédito', '19', TRUE, TRUE),
        ('NCR001', 'Nota de Crédito', '20', TRUE, TRUE),
        ('DEP001', 'Depósito', '20', TRUE, TRUE),
        ('TCP001', 'Tarjeta De Credito Por Pagar', '20', FALSE, TRUE),
        ('DEC001', 'Descuento En Compras', '20', FALSE, TRUE),
        ('GND001', 'Gastos No Deducible', '20', FALSE, TRUE),
        ('DCL001', 'Devolucion Clientes', '20', TRUE, FALSE)
) AS plantilla(codigo, nombre, codigo_sri, aplica_venta, aplica_compra)
JOIN formas_pago_sri sri ON sri.codigo = plantilla.codigo_sri
ON CONFLICT (empresa_id, punto_emision_id, codigo) DO NOTHING;

UPDATE empresas
SET sri_id = 1
WHERE slug ILIKE '%injoe%' OR slug ILIKE '%techcorp%' OR slug = 'injoedev';
