-- Facturas electrónicas e ítems. Idempotente.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_factura') THEN
        CREATE TYPE estado_factura AS ENUM (
            'BORRADOR',
            'ENVIADA',
            'PENDIENTE_AUTORIZACION',
            'AUTORIZADA',
            'RECHAZADA',
            'CANCELADA'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_receptor_factura') THEN
        CREATE TYPE tipo_receptor_factura AS ENUM ('cliente', 'consumidor_final');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS facturas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id),
    punto_emision_id INTEGER NOT NULL REFERENCES puntos_emision(id),
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
    cliente_id INTEGER REFERENCES clientes(id),
    orden_trabajo_id INTEGER REFERENCES ordenes_trabajo(id),
    forma_pago_id INTEGER REFERENCES formas_pago(id),
    numero VARCHAR(20) NOT NULL,
    tipo_receptor tipo_receptor_factura NOT NULL DEFAULT 'cliente',
    estado estado_factura NOT NULL DEFAULT 'BORRADOR',
    clave_acceso VARCHAR(64),
    xml_content TEXT,
    reason_error TEXT,
    numero_autorizacion VARCHAR(60),
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE,
    fecha_pago DATE,
    fecha_autorizacion TIMESTAMPTZ,
    subtotal_15 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_5 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_0 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_objeto NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_exento NUMERIC(12, 2) NOT NULL DEFAULT 0,
    iva_15 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    iva_5 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ice NUMERIC(12, 2) NOT NULL DEFAULT 0,
    irbpnr NUMERIC(12, 2) NOT NULL DEFAULT 0,
    descuento NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    notas TEXT,
    terminos TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    CONSTRAINT uq_facturas_numero_punto UNIQUE (empresa_id, punto_emision_id, numero)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_facturas_clave_acceso
    ON facturas (clave_acceso)
    WHERE clave_acceso IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_facturas_orden_activa
    ON facturas (orden_trabajo_id)
    WHERE orden_trabajo_id IS NOT NULL AND estado <> 'CANCELADA';

CREATE INDEX IF NOT EXISTS ix_facturas_empresa_id ON facturas (empresa_id);
CREATE INDEX IF NOT EXISTS ix_facturas_punto_emision_id ON facturas (punto_emision_id);
CREATE INDEX IF NOT EXISTS ix_facturas_cliente_id ON facturas (cliente_id);
CREATE INDEX IF NOT EXISTS ix_facturas_estado ON facturas (estado);
CREATE INDEX IF NOT EXISTS ix_facturas_fecha_emision ON facturas (fecha_emision);

CREATE TABLE IF NOT EXISTS facturas_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id INTEGER NOT NULL REFERENCES facturas(id) ON DELETE CASCADE,
    producto_id INTEGER REFERENCES productos(id),
    servicio_id INTEGER REFERENCES servicios(id),
    descripcion VARCHAR(500) NOT NULL,
    codigo VARCHAR(50),
    cantidad NUMERIC(10, 2) NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    descuento_porcentaje NUMERIC(5, 2) NOT NULL DEFAULT 0,
    aplica_iva BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_impuesto tipo_impuesto NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    iva_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ice_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    irbpnr_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_facturas_items_tipo CHECK (
        (producto_id IS NOT NULL AND servicio_id IS NULL)
        OR (producto_id IS NULL AND servicio_id IS NOT NULL)
    ),
    CONSTRAINT ck_facturas_items_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_facturas_items_precio CHECK (precio_unitario >= 0)
);

CREATE INDEX IF NOT EXISTS ix_facturas_items_factura_id ON facturas_items (factura_id);
