from typing import Protocol

from app.modules.proveedores.application.dto import ListarProveedoresQuery
from app.modules.proveedores.domain.entities import PrecioProveedor, Proveedor


class ProveedorRepository(Protocol):
    async def obtener_por_id(self, proveedor_id: int, empresa_id: int, punto_emision_id: int) -> Proveedor | None: ...

    async def obtener_por_identificacion(
        self, identificacion: str, empresa_id: int, punto_emision_id: int
    ) -> Proveedor | None: ...

    async def listar(
        self, empresa_id: int, punto_emision_id: int, query: ListarProveedoresQuery
    ) -> tuple[list[Proveedor], int]: ...

    async def guardar(self, proveedor: Proveedor) -> Proveedor: ...

    async def eliminar(self, proveedor_id: int, empresa_id: int, punto_emision_id: int) -> bool: ...

    async def esta_en_uso(self, proveedor_id: int) -> bool: ...


class PrecioProveedorRepository(Protocol):
    async def listar_producto(self, producto_id: int, empresa_id: int, punto_emision_id: int) -> list[PrecioProveedor]: ...

    async def listar_servicio(self, servicio_id: int, empresa_id: int, punto_emision_id: int) -> list[PrecioProveedor]: ...

    async def obtener(self, relacion_id: int) -> PrecioProveedor | None: ...

    async def obtener_par_producto(self, producto_id: int, proveedor_id: int) -> PrecioProveedor | None: ...

    async def obtener_par_servicio(self, servicio_id: int, proveedor_id: int) -> PrecioProveedor | None: ...

    async def guardar(self, precio: PrecioProveedor) -> PrecioProveedor: ...

    async def eliminar(self, relacion_id: int) -> bool: ...
