from typing import Protocol

from app.modules.configuracion.domain.entities import EmpresaConfig, PuntoEmisionConfig


class EmpresaConfigRepository(Protocol):
    async def obtener(self, empresa_id: int) -> EmpresaConfig | None: ...
    async def actualizar(self, empresa: EmpresaConfig) -> EmpresaConfig: ...


class PuntoConfigRepository(Protocol):
    async def listar(self, empresa_id: int) -> list[PuntoEmisionConfig]: ...
    async def obtener(self, punto_id: int, empresa_id: int) -> PuntoEmisionConfig | None: ...
    async def obtener_por_codigo(self, empresa_id: int, codigo: str, punto_emision: str) -> PuntoEmisionConfig | None: ...
    async def guardar(self, punto: PuntoEmisionConfig) -> PuntoEmisionConfig: ...
    async def eliminar(self, punto_id: int, empresa_id: int) -> bool: ...
    async def sembrar_formas_pago(self, empresa_id: int, punto_emision_id: int) -> None: ...
    async def asignar_usuario(self, usuario_id: int, punto_emision_id: int) -> None: ...
